### ISSUE TITLE
Background color not updated on TV version

### ISSUE THREAD

**Issue by loicgreffier** [michelin/suricate#683]
**Describe the bug**
Changing the background color of the dashboard is not displayed on the TV version

**To Reproduce**
- Display a dashboard on a TV
- Change the background color
- The background color is not changed on the TV version

**Expected behavior**
The background color should change on the TV

**Comment by maximemf** [comment]
Another improvement related to the background color of a dashboard:

Currently the background color only appears when at least one widget has been added to the dashboard

The background color should be displayed even when no widget has been added to the dashboard yet, otherwise users might think this featue isn't working if they created a dashboard with a background color and don't see this background applied
